<?php

namespace AppBundle\Repository;

/**
 * BewertungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BewertungRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComments($id) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('c , u.username as username')
            ->from('AppBundle:Bewertung','c')
            ->leftJoin('AppBundle:User', 'u', 'WITH', 'c.userId = u.id')
            ->where('c.placesId = :id')
            ->setParameter('id',$id);
        return $query->getQuery()->getResult();
    }

    public function getAverageRating() {

    }
}
