<?php

namespace AppBundle\Repository;

/**
 * PlacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacesRepository extends \Doctrine\ORM\EntityRepository
{
    public function topRated() {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('p','c')
            ->from('AppBundle:Bewertung','c')
            ->innerJoin('AppBundle:Places','p')
            ->where('c.placesId = p.id')
            ->setMaxResults(3)
            ->orderBy('c.bewertungen','DESC');
        print_r($query->getQuery()->getResult());
        return $query->getQuery()->getResult();
    }
}
