<?php

namespace AppBundle\Repository;

/**
 * PlacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacesRepository extends \Doctrine\ORM\EntityRepository
{
    public function topRated()
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('p', 'c.bewertungen as bewertungen')
            ->from('AppBundle:Places', 'p')
            ->leftJoin('AppBundle:Bewertung', 'c', 'WITH', 'p.id = c.placesId');

        return $query->getQuery()->getResult();
    }

    public function recommended()
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Bewertung', 'c')
            ->leftJoin('AppBundle:Places', 'p', 'WITH', 'p.id = c.placesId');

        $averageRating = $query->getQuery()->getResult();

//        for ($i = 1; $i <= $averageRating['placesId']; $i++) {
//
//        }
    }
}
